# Section One: Hopfield Network

## 1.3. Storing Pattern

In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
weights = np.ndarray((4, 4), dtype=int, buffer=np.full(16, 0))

patterns = [[1, 1, 1, 1], [-1, -1, -1, -1], [1, 1, -1, -1], [-1, -1, 1, 1]]

In [8]:
for pattern in patterns: 
    for i in range(4):
        for j in range(4): 
            if i == j:
                weights[i, j] = -50
                break
            weights[i, j] += pattern[i] * pattern[j]
            weights[j, i] = weights[i, j]
            
print(weights)

[[-50   4   0   0]
 [  4 -50   0   0]
 [  0   0 -50   4]
 [  0   0   4 -50]]


In [9]:
patterns_test = [
    [1, 1, -1, 1],
    [1, 1, -1, -1],
    [1, 1, 1, 1],
    [1, 1, 1, -1],
    [1, -1, -1, 1],
    [1, -1, -1, -1],
    [1, -1, 1, 1],
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [-1, 1, -1, -1],
    [-1, 1, 1, 1],
    [-1, 1, 1, -1],
    [-1, -1, -1, 1],
    [-1, -1, -1, -1],
    [-1, -1, 1, 1],
    [-1, -1, 1, -1]
]
Energy = []

for pattern in patterns_test:
    Energy.append(0)
    for i in range(4):
        for j in range(i):
            Energy[-1] -= weights[i][j] * pattern[i] * pattern[j]
            
print(patterns_test)         
print(Energy)

[[1, 1, -1, 1], [1, 1, -1, -1], [1, 1, 1, 1], [1, 1, 1, -1], [1, -1, -1, 1], [1, -1, -1, -1], [1, -1, 1, 1], [1, -1, 1, -1], [-1, 1, -1, 1], [-1, 1, -1, -1], [-1, 1, 1, 1], [-1, 1, 1, -1], [-1, -1, -1, 1], [-1, -1, -1, -1], [-1, -1, 1, 1], [-1, -1, 1, -1]]
[0, -8, -8, 0, 8, 0, 0, 8, 8, 0, 0, 8, 0, -8, -8, 0]


    - As can be seen, the 4 patterns have the minimum energy (-8), So they are storable in the network.

## 1.4. Design Hopfield Network

In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
def sign(X):
    if X < 0:
        return -1
    else:
        return 1

In [12]:
patterns = [[1, 1, 1, -1, -1, -1], [1, -1, 1, -1, 1, -1]]
weights = np.ndarray((6, 6), dtype=int, buffer=np.full(36, 0))

In [17]:
for pattern in patterns:
    print(len(pattern))
    for i in range(len(pattern)):
        for j in range(len(pattern)):
            if i == j:
                weights[i, j] = -50
                break
            weights[i, j] += pattern[i] * pattern[j]
            weights[j, i] = weights[i, j]

6
6


In [19]:
def is_pattern_stable(pattern, weights): 
    final = []
    temp_sum = []
#     print(len(pattern))
    for i in range(len(pattern)):
        temp_sum = []
        for j in range(len(weights[i])):
            if i == j: 
                continue
            temp_sum.append(pattern[j] * weights[i][j]) 
        final.append(sign(np.sum(temp_sum)))
    return final

patterns_test = [
    [1, 1, 1, -1, -1, -1],
    [1, -1, 1, -1, 1, -1],
    [-1, 1, 1, -1, -1, -1],
]
outputs = []
for pattern in patterns_test:
    outputs.append(is_pattern_stable(pattern, weights))

# print(patterns_test)
print(outputs)

[[1, 1, 1, -1, -1, -1], [1, -1, 1, -1, 1, -1], [1, 1, 1, -1, -1, -1]]


    - As we can see, output of the network for [1, 1, 1, -1, -1, -1] and [1, -1, 1, -1, 1, -1] is the same as them, so these two patterns are stable, But for [-1, 1, 1, -1, -1, -1], there is a noise in it and the network is able to remove the noise as we can see.